// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBouwlM08HZtKeo9RNtLwRM4qkWuf_A93Q',
    appId: '1:240272622591:web:05973705387830a078ddca',
    messagingSenderId: '240272622591',
    projectId: 'g4-academie',
    authDomain: 'g4-academie.firebaseapp.com',
    storageBucket: 'g4-academie.appspot.com',
    measurementId: 'G-HZN7TXFCDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE8aiJz91HSc-OB1Kmdsoq4p0PC8y7VII',
    appId: '1:240272622591:android:cd9c638df3abffdf78ddca',
    messagingSenderId: '240272622591',
    projectId: 'g4-academie',
    storageBucket: 'g4-academie.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgJ5BjedgnlEJADdOetXmcnQ7GIj4Y5MU',
    appId: '1:240272622591:ios:26a55f2717b12bc078ddca',
    messagingSenderId: '240272622591',
    projectId: 'g4-academie',
    storageBucket: 'g4-academie.appspot.com',
    iosBundleId: 'com.example.g4Academie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgJ5BjedgnlEJADdOetXmcnQ7GIj4Y5MU',
    appId: '1:240272622591:ios:26a55f2717b12bc078ddca',
    messagingSenderId: '240272622591',
    projectId: 'g4-academie',
    storageBucket: 'g4-academie.appspot.com',
    iosBundleId: 'com.example.g4Academie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBouwlM08HZtKeo9RNtLwRM4qkWuf_A93Q',
    appId: '1:240272622591:web:2e0561ae924804d378ddca',
    messagingSenderId: '240272622591',
    projectId: 'g4-academie',
    authDomain: 'g4-academie.firebaseapp.com',
    storageBucket: 'g4-academie.appspot.com',
    measurementId: 'G-012DPS7DCW',
  );

}