// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDShm4peaTKi4sXEOqkmGMhFxQQhIW3PWo',
    appId: '1:885901101157:web:d607ced6f077eb2f101e8c',
    messagingSenderId: '885901101157',
    projectId: 'g4-academie-fe1d3',
    authDomain: 'g4-academie-fe1d3.firebaseapp.com',
    storageBucket: 'g4-academie-fe1d3.appspot.com',
    measurementId: 'G-0PSS1PHFFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5zeADyIWf85V_IiG8T4NnV_Q4YBH2r64',
    appId: '1:885901101157:android:3441e7063abd41a3101e8c',
    messagingSenderId: '885901101157',
    projectId: 'g4-academie-fe1d3',
    storageBucket: 'g4-academie-fe1d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK2WXgzNr7zJ6vm9Z9Gh-x2Wr9SWUGGQU',
    appId: '1:885901101157:ios:e199be6827723c27101e8c',
    messagingSenderId: '885901101157',
    projectId: 'g4-academie-fe1d3',
    storageBucket: 'g4-academie-fe1d3.appspot.com',
    androidClientId: '885901101157-c1dvv2apsku11ioum96juh27ngqlt3tf.apps.googleusercontent.com',
    iosClientId: '885901101157-dqcsejoemiv5f0g94gev94oestp2qvmb.apps.googleusercontent.com',
    iosBundleId: 'com.example.g4Academie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK2WXgzNr7zJ6vm9Z9Gh-x2Wr9SWUGGQU',
    appId: '1:885901101157:ios:e199be6827723c27101e8c',
    messagingSenderId: '885901101157',
    projectId: 'g4-academie-fe1d3',
    storageBucket: 'g4-academie-fe1d3.appspot.com',
    androidClientId: '885901101157-c1dvv2apsku11ioum96juh27ngqlt3tf.apps.googleusercontent.com',
    iosClientId: '885901101157-dqcsejoemiv5f0g94gev94oestp2qvmb.apps.googleusercontent.com',
    iosBundleId: 'com.example.g4Academie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDShm4peaTKi4sXEOqkmGMhFxQQhIW3PWo',
    appId: '1:885901101157:web:20921ea3c5a56b1e101e8c',
    messagingSenderId: '885901101157',
    projectId: 'g4-academie-fe1d3',
    authDomain: 'g4-academie-fe1d3.firebaseapp.com',
    storageBucket: 'g4-academie-fe1d3.appspot.com',
    measurementId: 'G-JSEVG20YES',
  );

}